services:
  k8s-mcp-server:
    # Use either local build or official image from GitHub Packages
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile
    # Alternatively, use the pre-built multi-arch image
    # image: ghcr.io/yourusername/k8s-mcp-server:latest
    # Uncomment the ports section only if using SSE transport
    # ports:
    #   - "8080:8080"
    volumes:
      - ~/.kube:/home/appuser/.kube:ro # Mount Kubernetes configs as read-only
      # Uncomment to use custom security config
      # - ./security_config.yaml:/security_config.yaml:ro
    environment:
      # Kubernetes settings
      - K8S_CONTEXT=  # Leave empty to use current context or specify a context
      - K8S_NAMESPACE=default # Default namespace for commands
      
      # Security settings
      # - K8S_MCP_SECURITY_MODE=strict # strict (default) or permissive
      # - K8S_MCP_SECURITY_CONFIG=/security_config.yaml
      
      # Server settings
      - K8S_MCP_TIMEOUT=300 # Default timeout in seconds
      # - K8S_MCP_MAX_OUTPUT=100000 # Uncomment to set max output size
      - K8S_MCP_TRANSPORT=stdio # Transport protocol (stdio or sse)
    restart: unless-stopped
# To build multi-architecture images:
# 1. Set up Docker buildx: docker buildx create --name mybuilder --use
# 2. Build and push the multi-arch image:
#    docker buildx build --platform linux/amd64,linux/arm64 -t yourrepo/k8s-mcp-server:latest --push .
